name: git-fame

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 2.7.5

      - name: Rubocop
        run: bundle exec rubocop

  rspec:
    runs-on: ${{ matrix.os }}
    needs: [rubocop]
    strategy:
      matrix:
        ruby: ["2.7.5", "3.0.3", "3.1.0", "3.2.0", "3.3.0"]
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Install cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: Run tests
        run: bundle exec rspec --format RSpec::Github::Formatter --format progress --color --tty

      - name: Install gem locally
        run: bundle exec rake install:local

      - name: Run git-fame
        run: bundle exec exe/git-fame --log-level debug

      - name: Codeclimate (code coverage)
        if: runner.os != 'macos'
        uses: paambaati/codeclimate-action@v9
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          CI: true
        with:
          coverageLocations: ${{github.workspace}}/coverage/coverage.xml:cobertura
          coverageCommand: bundle exec rspec

  devcontainer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Set up devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Build devcontainer
        run: devcontainer build --workspace-folder .

      - name: Start devcontainer
        run: devcontainer up --workspace-folder .

      - name: Install dependencies
        run: devcontainer exec --workspace-folder . bundle exec rspec

  dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build docker image
        run: docker build -t git-fame -f .devcontainer/Dockerfile .

      - name: Test docker image
        run: docker run -it -v $(pwd):/workspace git-fame bundle exec rspec
